# Generated by Django 5.1.3 on 2024-11-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudInfoSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(choices=[('Classroom', 'Classroom'), ('Office', 'Office'), ('Library', 'Library'), ('Clinic', 'Clinic')], max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='StudInfoSys.facilityinventory')),
            ],
        ),
    ]
